### ISSUE TITLE
The latest version of the official YouTube cannot be patched.

### ISSUE THREAD

**Issue by w-all** [GuillaumeSmaha/youtube-webos-cobalt-app#11]
Greetings.
I downloaded the latest official version of youtube 1.1.44 (TV: OLED C2, web-os: 7.3.1-44), but when I try to patch it I get the error:
`File "libcobalt.so" is not present in your IPK. This patch is not compatible with your IPK version. make: *** [Makefile:122: workdir/ipk/content/app/cobalt/content/web/adblock] Error 1`
Using the **ls-monitor** command via SSH, I saw that the TV installs two ipk: youtube.leanback.v4 in the /media/cryptofs folder and cobalt.shared in the /media/system folder.
I pulled out and attached both of these ipk.
Will you be able to see why there is a problem with patching the new version of youtube?
[2023-10-19-youtube.leanback.v4-1.1.44.zip](https://github.com/GuillaumeSmaha/youtube-webos-cobalt/files/13461513/2023-10-19-youtube.leanback.v4-1.1.44.zip)
[cobalt.shared.zip](https://github.com/GuillaumeSmaha/youtube-webos-cobalt/files/13461515/cobalt.shared.zip)

**Comment by GuillaumeSmaha** [comment]
Hi @wall25 
Interesting case. On my side. I have the same ipk with the combination of the your 2 ipks. 
LG provides a different way for your TV. My and your IPK were built at the same time:

Your IPK build info
```
cobalt_version: 22.lts.6
cobalt_build: 308696
cobalt_branch: 22.lts
commit_revision: daa9163647
build_target: egs_gold
soc: o22
oe_env: mlt4tv_260
build_time: 2023-06-13 13:07
build_env: Linux 400f4c44798d
```

My IPK build info
```
cobalt_version: 22.lts.6
cobalt_build: 308696
cobalt_branch: 22.lts
commit_revision: daa9163647
build_target: eg_gold
soc: o20n
oe_env: kcl4tv_253
build_time: 2023-06-13 12:42
build_env: Linux 400f4c44798d

```

**Comment by wall25** [comment]
> Let me know if it works :)

The patching process works fine, but the resulting application does not work. It tries to start and exits without messages.

**Comment by GuillaumeSmaha** [comment]
I moved all IPKs here: https://github.com/GuillaumeSmaha/youtube-webos-cobalt-ipks/

**Comment by 777stiv** [comment]
Hi GuillaumeSmaha
looks like there is a similar problem with the youtube 1.1.51 package for LG C3 webos 8.0.0-4601 fw 03.30.73 cobalt 23.lts.6
The package was downloaded using the method you described from the TV at the time of installation.
please help me patch this. 
[youtube.leanback.v4_2024.zip](https://github.com/GuillaumeSmaha/youtube-webos-cobalt-app/files/15501759/youtube.leanback.v4_2024.zip)

**Comment by w-all** [comment]
After the WebOS on the TV was updated to version 8.3.0, the installation of the Youtube client and Cobalt began to occur from one IPK.

**Comment by w-all** [comment]
After the WebOS on the TV was updated to version 8.3.0, the installation of the Youtube client and Cobalt began to occur from one IPK.
